### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by surbhit21** [surbhit21/GSoC-2019#3]
Hi,

I tried running the optimization and it seems that there is some issue with the unzipping. I am adding the error trace.
`Internal Server Error: /tasks/Optimization/
Traceback (most recent call last):
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/surbhit/Work/GSoC-2019/venv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/surbhit/Work/GSoC-2019/GSoC-2019/REST_FindSim/tasks/views.py", line 68, in create
    os.mkdir(os.path.join(BASE_FILE_PATH, 'tsv/')+file_label)
FileNotFoundError: [Errno 2] No such file or directory: 'media/files/tsv/surbhit11563865698.6517096'`

**Comment by ClockworkHou** [comment]
Hi, I think this happens when using os.mkdir() and pyrhon fails to find the directory"media/files/tsv/". I will add this empty directory into repo. Hope this can fix the problem.

**Comment by surbhit21** [comment]
I am having the "media/files/tsv/" directory and the zip is also getting stored there but the specific folder is not created in this case the `surbhit11563865698.6517096` folder

**Comment by clockworkgenius** [comment]
Maybe it's because the path here is a relative path rather than a absolute path?

**Comment by ClockworkHou** [comment]
I knew the reason. It's because os.mkdir() can not create dir in a complicated path. I changed this into os.makedirs(). I think this will solve the problem.

**Comment by surbhit21** [comment]
The os.makedirs(), did not solve the error on my machine. Is there anything else I have to do besides pulling the last commit and running it? Also, the folders are created but they are empty.
`FileNotFoundError at /tasks/Optimization/
[Errno 2] No such file or directory: 'media/files/tsv/surbhit11563881005.749884/testop.zip'`

**Comment by ClockworkHou** [comment]
I think you need to migrate. Because the models are changed and the tsv files and model files are uploading into media/files/tsv/ and media/files/model/ respectively.
I have done 'makemigration' operation on my machine and upload the migration into repo.
But I think you need to do 'migrate' operation on your machine.

**Comment by surbhit21** [comment]
Thanks Chen, migrating worked like a charm. It is running on my machine now. :)
